nginx-ingress:
  controller:
    #config:
      #ssl-redirect: "false"
      #hsts: "false"
    service:
      type: LoadBalancer
            
ingress:
  enabled: true
  nginxController: true
  annotations: {}
    #ingress.kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
  - host: easydoggie.example.com
    enabled: true
    serviceName: nginx
    servicePort: 80
  - host: gitea.example.com
    enabled: true
    serviceName: gitea
    servicePort: 3000
  - host: adminer.example.com
    enabled: true
    serviceName: adminer
    servicePort: 80
  - host: kibana.example.com
    enabled: true
    serviceName: kibana-kibana
    servicePort: 5601
  - host: grafana.example.com
    enabled: true
    serviceName: grafana
    servicePort: 80
  - host: drone.example.com
    enabled: true
    serviceName: drone-drone
    servicePort: 80

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local