baseURL = "https://easydoggie.github.io/EasyDoggie/"
title = "EasyDoggie"
theme = "hugo-theme-learn"
pygmentsStyle = "monokai"
pygmentsCodefences = true
publishdir = "../docs/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "red"