nginx-ingress:
    controller:
        service:
            type: LoadBalancer
            
ingress:
  enabled: true
  annotations: 
    ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - path: /gitea
      serviceName: gitea
      servicePort: 80

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local