nginx-ingress:
    controller:
        #config:
            #ssl-redirect: "false"
            #hsts: "false"
        service:
            type: LoadBalancer
            
ingress:
  enabled: true
  annotations: 
    ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
  paths:
    - path: /easydoggie(/|$)(.*)
      serviceName: nginx
      servicePort: 80
    - path: /gitea(/|$)(.*)
      serviceName: gitea
      servicePort: 3000

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local