# file: node/values.yaml

replicaCount: 1

image:
  repository: node
  tag: 10.16.0-alpine
  pullPolicy: IfNotPresent

imageInit:
  repository: alpine/git
  tag: latest
  pullPolicy: IfNotPresent
  command: []
  args:
    - clone
    - https://github.com/easydoggie/testapp.git
    - /tmp/git

nameOverride: ""
fullnameOverride: "node"

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

nginx-ingress:
  enabled: false
  
ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
