# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: 1.16.0-alpine
  pullPolicy: IfNotPresent

imageUnit:
  repository: nginx/unit
  tag: 1.9.0-full
  pullPolicy: IfNotPresent

imageInit:
  alpine:
    repository: alpine/git
    tag: latest
    pullPolicy: IfNotPresent
    command: |-
      - ""
    args: |-
      - "clone"
      - "https://github.com/easydoggie/testapp.git"
      - "/tmp/git"
  python:
    enabled: true
    repository: python
    tag: 3.5-alpine
    pullPolicy: IfNotPresent
    command: |-
      - "/bin/sh"
      - "-c"
      - "apk add git; \
         git clone https://github.com/easydoggie/testapp.git /tmp/git; \
         python -m venv /tmp/git/python/venv; \
         . /tmp/git/python/venv/bin/activate; \
         pip install redis"
    args: |-
      - ""
  
appServer:
  enabled: true
  serverName: localhost
  port: 8300
  
nameOverride: ""
fullnameOverride: "nginx"
  
service:
  type: NodePort
  port: 80
  targetPort: 80
  #nodePort: 30000
  
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
