replicaCount: 1

image:
  repository: nginx
  tag: 1.16.0-alpine
  pullPolicy: IfNotPresent

imageUnit:
  repository: nginx/unit
  tag: 1.9.0-full
  pullPolicy: IfNotPresent

imageInit:
  alpine:
    repository: alpine/git
    tag: latest
    pullPolicy: IfNotPresent
    command: |-
      - ""
    args: |-
      - "clone"
      - "https://github.com/easydoggie/testapp.git"
      - "/tmp/git"
  python:
    repository: python
    tag: 3.5-alpine
    pullPolicy: IfNotPresent
    command: |-
      - "/bin/sh"
      - "-c"
      - "apk add git; \
         git clone https://github.com/easydoggie/testapp.git /tmp/git; \
         python -m venv /tmp/git/python/venv; \
         . /tmp/git/python/venv/bin/activate; \
         pip install redis"
    args: |-
      - ""
  
appServer:
  enabled: true
  port: 8300
  applications:
    name: testapp
    type: python 3.5
    processes: 1
    workingDirectory: /app/python
    user: www-data
    group: www-data
    timeout: 10
    requests: 1000
    python:
      module: index
  settings:
    headerReadTimeout: 30
    bodyReadTimeout: 30
    sendTimeout: 30
    idleTimeout: 180
    maxBodySize: 8388608
  
nameOverride: ""
fullnameOverride: "nginx"
  
service:
  type: NodePort
  port: 80
  targetPort: 80
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
