# kibana/kibana/values.yaml
kibana:
  nameOverride: kibana
  elasticsearchHosts: http://elasticsearch-master:9200
  kibanaConfig:
    kibana.yml: |
      server:
        host: 0.0.0.0
  resources:
    requests:
      memory: 128Mi