apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-conf
data:
  default.conf: |-
    {{- if .Values.appServer.enabled }}
    upstream unit_backend {
       server {{ .Values.appServer.serverName }}:{{ .Values.appServer.port }};
    }
    {{- end }}
    
    server {
        listen       80;
        server_name  localhost;
            
        location / {
            root /usr/share/nginx/html;
            index index.html;
        } 
        {{- if .Values.appServer.enabled -}}
        location /api {
            proxy_pass http://unit_backend;
            proxy_set_header Host $host;
        }
        {{- end }}
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    
    }
  unit.conf.json: |-
    {
      "listeners": {
        "*:{{ .Values.appServer.port }}": {
          "pass": "applications/testapp"
        }
      },  
      "applications": {
        "testapp": {
          "type": "python 3.5",
          "processes": 2,
          "working_directory": "/app/python",
          "path": "/app/python/testapp",
          "home": "/app/python/venv",
          "module": "index",
          "user": "root",
          "group": "root",
          "limits": {
              "timeout": 10,
              "requests": 1000
          }
        }
      },
      "settings": {
          "http": {
              "header_read_timeout": 10,
              "body_read_timeout": 10,
              "send_timeout": 10,
              "idle_timeout": 120,
              "max_body_size": 6291456
          }
      },
    }
