apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-conf
data:
  default.conf: |-
    {{- if .Values.appServer.enabled }}
    upstream unit_backend {
       server localhost:{{ .Values.appServer.port }};
    }
    {{- end }}
    
    server {
        listen       {{ .Values.service.targetPort }};
        server_name  localhost;
            
        location / {
            root /usr/share/nginx/html;
            index index.html;
        } 
        {{- if .Values.appServer.enabled -}}
        location /api {
            proxy_pass http://unit_backend;
            proxy_set_header Host $host;
        }
        {{- end }}
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    
    }
  unit.conf.json: |-
    {
      "listeners": {
        "*:{{ .Values.appServer.port }}": {
          "pass": "applications/{{ .Values.appServer.applications.name }}"
        }
      },  
      "applications": {
        "{{ .Values.appServer.applications.name }}": {
          "type": "{{ .Values.appServer.applications.type }}",
          "processes": {{ .Values.appServer.applications.processes }},
          "working_directory": "{{ .Values.appServer.applications.workingDirectory }}",
          "user": "{{ .Values.appServer.applications.user }}",
          "group": "{{ .Values.appServer.applications.group }}",
          {{- if contains "python" .Values.appServer.applications.type }}
          "path": "/app/python/{{ .Values.appServer.applications.name }}",
          "home": "/app/python/venv",
          "module": "{{ .Values.appServer.applications.python.module }}",
          {{- end }}
          "limits": {
              "timeout": {{ int .Values.appServer.applications.timeout }},
              "requests": {{ int .Values.appServer.applications.requests }}
          }
        }
      },
      "settings": {
          "http": {
              "header_read_timeout": {{ int .Values.appServer.settings.headerReadTimeout }},
              "body_read_timeout": {{ int .Values.appServer.settings.bodyReadTimeout }},
              "send_timeout": {{ int .Values.appServer.settings.sendTimeout }},
              "idle_timeout": {{ int .Values.appServer.settings.idleTimeout }},
              "max_body_size": {{ int .Values.appServer.settings.maxBodySize }}
          }
      },
    }
