replicaCount: 1

image:
  repository: easydoggie/adminer
  tag: 0.1.17
  pullPolicy: IfNotPresent

imageNginx:
  repository: nginx
  tag: 1.17.3-alpine
  pullPolicy: IfNotPresent
  
nameOverride: ""
fullnameOverride: "adminer"
  
service:
  type: NodePort
  port: 80
  targetPort: 80
  
appServer:
  port: 8300

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
