apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-volume
spec:
  storageClassName: nginx-unit-hdd
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pv-claim
spec:
  storageClassName: nginx-unit-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
