dependencies:
  - name: nginx
    version: 0.1.3
    repository: "@easydoggie"
    #repository: "@local"
  - name: nginx-unit
    version: 0.1.1
    repository: "@easydoggie"
    #repository: "@local"
  - name: node 
    version: 0.1.3
    repository: "@easydoggie"
    #repository: "@local"
  - name: nginx-ingress
    version: 0.1.0
    repository: "@easydoggie"
    #repository: "@local"
  - name: gitea
    version: 0.1.0
    repository: "@easydoggie"
    #repository: "@local"
