dependencies:
  - name: adminer
    version: 0.1.0
    repository: "@easydoggie"
  - name: drone
    version: 0.1.0
    repository: "@easydoggie"
  - name: elasticsearch
    version: 0.1.0
    repository: "@easydoggie"
  - name: fluentd
    version: 0.1.0
    repository: "@easydoggie"
  - name: gitea
    version: 0.1.2
    repository: "@easydoggie"
  - name: ingress
    version: 0.1.5
    repository: "@easydoggie"
  - name: kibana
    version: 0.1.1
    repository: "@easydoggie"
  - name: mysql
    version: 0.1.0
    repository: "@easydoggie"
  - name: nginx
    version: 0.1.4
    repository: "@easydoggie"
  - name: node 
    version: 0.1.4
    repository: "@easydoggie"
  - name: prometheus
    version: 0.1.1
    repository: "@easydoggie"
  - name: redis
    version: 0.1.1
    repository: "@easydoggie"