apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  proxysql.cnf: |-
    datadir="/var/lib/proxysql"
    
    admin_variables=
    {
        admin_credentials="{{ .Values.proxysql.admin.user }}:{{ .Values.proxysql.admin.password }}"
        mysql_ifaces="0.0.0.0:{{ .Values.service.adminPort.port }}"
        refresh_interval=2000
    }
    
    mysql_variables=
    {
        threads=4
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:{{ .Values.service.servicePort.port }};/tmp/proxysql.sock"
        default_schema="information_schema"
        stacksize=1048576
        server_version="5.1.30"
        connect_timeout_server=10000
        monitor_history=60000
        monitor_connect_interval=200000
        monitor_ping_interval=200000
        ping_interval_server_msec=10000
        ping_timeout_server=200
        commands_stats=true
        sessions_sort=true
        monitor_username={{ .Values.proxysql.monitor.user | quote }}
        monitor_password={{ .Values.proxysql.monitor.password | quote }}
    }
    
    mysql_replication_hostgroups =
    (
        { writer_hostgroup=10 , reader_hostgroup=20 , comment="host groups" }
    )
    
    mysql_servers =
    (
      {{- range .Values.proxysql.servers }}
        { address={{ .server | quote }} , port={{ .port }} , hostgroup={{ .hostgroup }}, max_connections={{ .maxConnections }} , max_replication_lag = 5 },
      {{- end }}
    )
    
    mysql_query_rules =
    (
        {
            rule_id=100
            active=1
            match_pattern="^SELECT .* FOR UPDATE"
            destination_hostgroup=10
            apply=1
        },
        {
            rule_id=200
            active=1
            match_pattern="^SELECT .*"
            destination_hostgroup=20
            apply=1
        },
        {
            rule_id=300
            active=1
            match_pattern=".*"
            destination_hostgroup=10
            apply=1
        }
    )
    
    mysql_users =
    (
      {{- range .Values.proxysql.users }}
        { username = {{ .user | quote }} , password = {{ .password | quote }} , default_hostgroup = {{ .hostgroup }} , active = 1 },
      {{- end }}
    )