apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-conf
data:
  app.ini: |-
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = dev
    
    [repository]
    ROOT = /data/git/repositories
    
    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo
    
    [repository.upload]
    TEMP_PATH = /data/gitea/uploads
    
    [server]
    APP_DATA_PATH    = /data/gitea
    SSH_DOMAIN       = {{ .Values.gitea.host }}
    HTTP_PORT        = 3000
    ROOT_URL         = http://{{ .Values.gitea.host }}:{{ .Values.gitea.ingressPort }}/gitea/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    LFS_CONTENT_PATH = /data/git/lfs
    
    [database]
    PATH    = /data/gitea/gitea.db
    DB_TYPE = sqlite3
    HOST    = localhost:3306
    NAME    = gitea
    USER    = root
    PASSWD  = 
    
    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
    
    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    
    [picture]
    AVATAR_UPLOAD_PATH = /data/gitea/avatars
    
    [attachment]
    PATH = /data/gitea/attachments
    
    [log]
    ROOT_PATH = /data/gitea/log
    
    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = 
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1NTgzMzMxNDN9.H1RpzbneY8VqlFqzIB9Uba7NXlfqk-Bp5BPTVCn2y-4
    
    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW  = false
    
    [oauth2]
    JWT_SECRET = 6daV-4tGginmubYVDjwvGbHRSLu-NDBxy8JFa1dmt6E