dependencies:
  - name: nginx
    version: 0.1.1
    repository: "@sumomo99-stable"
    #repository: "@local"
  - name: nginx-unit-python 
    version: 0.1.0
    repository: "@sumomo99-stable"
    #repository: "@local"
  - name: node 
    version: 0.1.2
    repository: "@sumomo99-stable"
    #repository: "@local"
